#!/usr/bin/env bash
KAZOO_WEB="http://downcc.ucserver.org:8082/RPMS/kazoo.tar.gz"
kazoo_packages{
  cd /usr/src
  if [ ! -e ./kazoo.tar.gz ]; then
			wget $KAZOO_WEB
  fi;
}
kazoo_packages
/opt/kazoo_install/setup_packages -a -i bigcouch -i rabbitmq -i haproxy -i kazoo -i freeswitch -i kamailio -i monster-ui



